# Configuracion de MySQL en la NUBE (Railway)
# Reemplaza los datos con los que copiaste de Railway:
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=skqvhbPkAGhYaqLUmWziHddtxsRlqRUe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de Hibernate
spring.jpa.show-sql=true
# 🔥 IMPORTANTE: Cambia 'none' a 'update' para que Railway cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect